import Header from "@/Component/Shared/Header";
import "./globals.css";
import Container from "@/Component/UI/Container";

export const metadata = {
  title: "Job Application Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Container>
          
          <Header />
          {children}
        </Container>
      </body>
    </html>
  );
}
